spring:
#  application:
#    name: program-service
  mvc:
    problemdetails:
      enabled: true

  data:
    mongodb:
      uri: mongodb://root:5ZgRndBwuw7oud-LYWtGM1whPln4sSAF0OKnDnx6ReWP4Ilq@3173a6f3-1ba8-4d76-b68f-0d9a49e0c8d1.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false



server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9001/eureka  # ← missing, this is why it hits 8761
#  instance:
#    prefer-ip-address: true







