spring:
#  application:
#    name: program-service
  mvc:
    problemdetails:
      enabled: true

  data:
    mongodb:
      host: localhost
      port: 13500
      database: eca
      username: root
      password: mongodb
      authentication-database: admin


server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9001/eureka  # ← missing, this is why it hits 8761
#  instance:
#    prefer-ip-address: true







